/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesión por cookie HttpOnly. Nunca devuelve token */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesión actual */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lotes por vencimiento ascendente y luego id, con filtro opcional por producto (todo rol) */
        get: operations["lots.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario de la sesión con las capacidades de su rol */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Productos ordenados por nombre (todo rol) */
        get: operations["products.index"];
        put?: never;
        /** Crea un producto (solo admin) */
        post: operations["products.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica parcialmente un producto (solo admin) */
        patch: operations["products.update"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuarios ordenados por nombre (solo admin) */
        get: operations["users.index"];
        put?: never;
        /** Crea un usuario con un rol (solo admin) */
        post: operations["users.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bodegas ordenadas por nombre (todo rol) */
        get: operations["warehouses.index"];
        put?: never;
        /** Crea una bodega (solo admin) */
        post: operations["warehouses.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses/{warehouse}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica parcialmente una bodega (solo admin) */
        patch: operations["warehouses.update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            /**
             * @description Código estable del rechazo (contrato con la SPA).
             * @enum {string}
             */
            code: "unauthenticated" | "forbidden" | "not_found" | "csrf_token_mismatch" | "validation_failed" | "invalid_credentials" | "too_many_attempts" | "method_not_allowed" | "http_error" | "server_error";
            /** @description Mensaje en español para el usuario. */
            message: string;
            /** @description Mensajes en español por campo inválido. */
            errors?: {
                [key: string]: string[];
            };
        };
        /** AuthenticatedUserResource */
        AuthenticatedUserResource: {
            id: number;
            name: string;
            email: string;
            role: string;
            abilities: unknown[];
        };
        /**
         * LoginRequest
         * @description Login desde la SPA. Sin sesión (origen ajeno a SANCTUM_STATEFUL_DOMAINS, o sin Origin/Referer) se
         *     rechaza con 403 antes de validar: sin consulta a la base, sin limitador y sin cookie (design D1).
         */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** LotResource */
        LotResource: {
            id: number;
            product_id: number;
            lot_code: string;
            expires_on: string;
            is_expired: boolean;
        };
        /** ProductResource */
        ProductResource: {
            id: number;
            code: string;
            name: string;
            presentation: string | null;
            is_controlled: boolean;
        };
        /**
         * StoreProductRequest
         * @description Alta de producto (catalog "Alta de productos"): solo catalog.manage. Campos ajenos (p. ej. role) se ignoran.
         */
        StoreProductRequest: {
            code: string;
            name: string;
            presentation?: string | null;
            is_controlled?: boolean;
        };
        /**
         * StoreUserRequest
         * @description Alta de usuario (identity-access "Alta de usuarios"). El correo se normaliza antes de validar:
         *     la unicidad no distingue mayúsculas.
         */
        StoreUserRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "auxiliar_farmacia" | "regente_farmacia" | "medico" | "auditor" | "admin";
        };
        /**
         * StoreWarehouseRequest
         * @description Alta de bodega (catalog "Alta de bodegas"): solo catalog.manage.
         */
        StoreWarehouseRequest: {
            code: string;
            name: string;
        };
        /**
         * UpdateProductRequest
         * @description Modificación parcial de producto (catalog "Modificación de productos").
         */
        UpdateProductRequest: {
            code?: string;
            name?: string;
            presentation?: string | null;
            is_controlled?: boolean;
        };
        /**
         * UpdateWarehouseRequest
         * @description Modificación parcial de bodega (catalog "Modificación de bodegas"): mismas reglas del alta; la bodega
         *     puede conservar su propio código y nombre.
         */
        UpdateWarehouseRequest: {
            code?: string;
            name?: string;
        };
        /** UserResource */
        UserResource: {
            id: number;
            name: string;
            email: string;
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** @constant */
            code: "validation_failed";
            /** @description Mensaje en español para el usuario. */
            message: string;
            /** @description Mensajes en español por campo inválido. */
            errors: {
                [key: string]: string[];
            };
        };
        /** WarehouseResource */
        WarehouseResource: {
            id: number;
            code: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description `AuthenticatedUserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthenticatedUserResource"];
                    };
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos (code: validation_failed, con errors) o credenciales inválidas (code: invalid_credentials). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Demasiados intentos fallidos de login; ver Retry-After. code: too_many_attempts */
            429: {
                headers: {
                    /** @description Segundos hasta poder reintentar. */
                    "Retry-After": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "lots.index": {
        parameters: {
            query?: {
                product_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `LotResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LotResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AuthenticatedUserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthenticatedUserResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "products.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ProductResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "products.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreProductRequest"];
            };
        };
        responses: {
            /** @description `ProductResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "products.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The product ID */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description `ProductResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Recurso inexistente. code: not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "users.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "users.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUserRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "warehouses.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `WarehouseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WarehouseResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "warehouses.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreWarehouseRequest"];
            };
        };
        responses: {
            /** @description `WarehouseResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WarehouseResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "warehouses.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The warehouse ID */
                warehouse: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateWarehouseRequest"];
            };
        };
        responses: {
            /** @description `WarehouseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WarehouseResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Recurso inexistente. code: not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
