/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/kardex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movimientos del kardex, del más reciente al más antiguo, paginados (inventory.view) */
        get: operations["kardex.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesión por cookie HttpOnly. Nunca devuelve token */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesión actual */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lotes por vencimiento ascendente y luego id, con filtro opcional por producto (todo rol) */
        get: operations["lots.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario de la sesión con las capacidades de su rol */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Productos ordenados por nombre (todo rol) */
        get: operations["products.index"];
        put?: never;
        /** Crea un producto (solo admin) */
        post: operations["products.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica parcialmente un producto (solo admin) */
        patch: operations["products.update"];
        trace?: never;
    };
    "/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Existencias con cantidad mayor que 0, filtrables por bodega, producto y lote (inventory.view) */
        get: operations["stock.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock-adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ajusta una existencia con motivo y devuelve el movimiento `ajuste` creado (solo inventory.adjust) */
        post: operations["stock-adjustments.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuarios ordenados por nombre (solo admin) */
        get: operations["users.index"];
        put?: never;
        /** Crea un usuario con un rol (solo admin) */
        post: operations["users.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bodegas ordenadas por nombre (todo rol) */
        get: operations["warehouses.index"];
        put?: never;
        /** Crea una bodega (solo admin) */
        post: operations["warehouses.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses/{warehouse}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica parcialmente una bodega (solo admin) */
        patch: operations["warehouses.update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            /**
             * @description Código estable del rechazo (contrato con la SPA).
             * @enum {string}
             */
            code: "unauthenticated" | "forbidden" | "not_found" | "csrf_token_mismatch" | "validation_failed" | "invalid_credentials" | "too_many_attempts" | "insufficient_stock" | "lot_expired" | "method_not_allowed" | "http_error" | "server_error";
            /** @description Mensaje en español para el usuario. */
            message: string;
            /** @description Mensajes en español por campo inválido. */
            errors?: {
                [key: string]: string[];
            };
        };
        /** AuthenticatedUserResource */
        AuthenticatedUserResource: {
            id: number;
            name: string;
            email: string;
            role: string;
            abilities: unknown[];
        };
        /** KardexMovementResource */
        KardexMovementResource: {
            id: number;
            type: components["schemas"]["MovementType"];
            quantity: number;
            balance_after: number;
            reason: string | null;
            created_at: string;
            warehouse: components["schemas"]["WarehouseResource"];
            product: components["schemas"]["ProductSummaryResource"];
            lot: components["schemas"]["LotSummaryResource"];
            user: {
                id: number;
                name: string;
            } | null;
        };
        /**
         * LoginRequest
         * @description Login desde la SPA. Sin sesión (origen ajeno a SANCTUM_STATEFUL_DOMAINS, o sin Origin/Referer) se
         *     rechaza con 403 antes de validar: sin consulta a la base, sin limitador y sin cookie (design D1).
         */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** LotResource */
        LotResource: {
            id: number;
            product_id: number;
            lot_code: string;
            expires_on: string;
            is_expired: boolean;
        };
        /** LotSummaryResource */
        LotSummaryResource: {
            id: number;
            lot_code: string;
            expires_on: string;
            is_expired: boolean;
        };
        /**
         * MovementType
         * @description Tipos de movimiento del kardex (RN-06). Los literales son los de la regla; S3 y S4 escriben los suyos.
         * @enum {string}
         */
        MovementType: "entrada" | "salida_dispensacion" | "salida_traslado" | "entrada_traslado" | "ajuste";
        /** ProductResource */
        ProductResource: {
            id: number;
            code: string;
            name: string;
            presentation: string | null;
            is_controlled: boolean;
        };
        /** ProductSummaryResource */
        ProductSummaryResource: {
            id: number;
            code: string;
            name: string;
            is_controlled: boolean;
        };
        /** StockResource */
        StockResource: {
            id: number;
            quantity: number;
            warehouse: components["schemas"]["WarehouseResource"];
            product: components["schemas"]["ProductSummaryResource"];
            lot: components["schemas"]["LotSummaryResource"];
        };
        /**
         * StoreProductRequest
         * @description Alta de producto (catalog "Alta de productos"): solo catalog.manage. Campos ajenos (p. ej. role) se ignoran.
         */
        StoreProductRequest: {
            code: string;
            name: string;
            presentation?: string | null;
            is_controlled?: boolean;
        };
        /**
         * StoreStockAdjustmentRequest
         * @description Ajuste de inventario (inventory "Ajuste de inventario"): solo inventory.adjust. `reason` de solo espacios
         *     llega como null (TrimStrings + ConvertEmptyStringsToNull) y falla `required`. Usuario, tipo, saldo y fecha
         *     nunca se leen del cuerpo: solo `adjustment()` llega a la acción.
         */
        StoreStockAdjustmentRequest: {
            warehouse_id: number;
            lot_id: number;
            quantity: number;
            reason: string;
        };
        /**
         * StoreUserRequest
         * @description Alta de usuario (identity-access "Alta de usuarios"). El correo se normaliza antes de validar:
         *     la unicidad no distingue mayúsculas.
         */
        StoreUserRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "auxiliar_farmacia" | "regente_farmacia" | "medico" | "auditor" | "admin";
        };
        /**
         * StoreWarehouseRequest
         * @description Alta de bodega (catalog "Alta de bodegas"): solo catalog.manage.
         */
        StoreWarehouseRequest: {
            code: string;
            name: string;
        };
        /**
         * UpdateProductRequest
         * @description Modificación parcial de producto (catalog "Modificación de productos").
         */
        UpdateProductRequest: {
            code?: string;
            name?: string;
            presentation?: string | null;
            is_controlled?: boolean;
        };
        /**
         * UpdateWarehouseRequest
         * @description Modificación parcial de bodega (catalog "Modificación de bodegas"): mismas reglas del alta; la bodega
         *     puede conservar su propio código y nombre.
         */
        UpdateWarehouseRequest: {
            code?: string;
            name?: string;
        };
        /** UserResource */
        UserResource: {
            id: number;
            name: string;
            email: string;
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** @constant */
            code: "validation_failed";
            /** @description Mensaje en español para el usuario. */
            message: string;
            /** @description Mensajes en español por campo inválido. */
            errors: {
                [key: string]: string[];
            };
        };
        /** WarehouseResource */
        WarehouseResource: {
            id: number;
            code: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "kardex.index": {
        parameters: {
            query?: {
                warehouse_id?: number;
                product_id?: number;
                lot_id?: number;
                per_page?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `KardexMovementResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KardexMovementResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description `AuthenticatedUserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthenticatedUserResource"];
                    };
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos (code: validation_failed, con errors) o credenciales inválidas (code: invalid_credentials). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Demasiados intentos fallidos de login; ver Retry-After. code: too_many_attempts */
            429: {
                headers: {
                    /** @description Segundos hasta poder reintentar. */
                    "Retry-After": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "lots.index": {
        parameters: {
            query?: {
                product_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `LotResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LotResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AuthenticatedUserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthenticatedUserResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "products.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ProductResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "products.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreProductRequest"];
            };
        };
        responses: {
            /** @description `ProductResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "products.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The product ID */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description `ProductResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Recurso inexistente. code: not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "stock.index": {
        parameters: {
            query?: {
                warehouse_id?: number;
                product_id?: number;
                lot_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `StockResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StockResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "stock-adjustments.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreStockAdjustmentRequest"];
            };
        };
        responses: {
            /** @description `KardexMovementResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KardexMovementResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description La operación dejaría la existencia negativa o la existencia no existe. code: insufficient_stock */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos (code: validation_failed, con errors) o ingreso a un lote vencido (code: lot_expired). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "users.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "users.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUserRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "warehouses.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `WarehouseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WarehouseResource"][];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "warehouses.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreWarehouseRequest"];
            };
        };
        responses: {
            /** @description `WarehouseResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WarehouseResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    "warehouses.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The warehouse ID */
                warehouse: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateWarehouseRequest"];
            };
        };
        responses: {
            /** @description `WarehouseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WarehouseResource"];
                    };
                };
            };
            /** @description Sin sesión. code: unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Sin permiso para el rol, o login desde un origen ajeno a la SPA. code: forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Recurso inexistente. code: not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Falta X-XSRF-TOKEN o no corresponde a la sesión. code: csrf_token_mismatch */
            419: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos. code: validation_failed, con errors por campo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
