// Módulo central de textos de la interfaz. Todo texto visible sale de aquí, en español (ADR-0006).
// Las plantillas usan marcadores `{nombre}` y se completan con `format()`.
export const strings = {
  app: {
    name: 'Dispensart',
    // Error de arranque si `index.html` no trae el contenedor; no llega a la interfaz.
    missingRoot: 'No existe el elemento #root en index.html',
  },
  shell: {
    welcomeTitle: 'Bienvenido',
    welcomeMessage:
      'Dispensación de medicamentos, inventario por lote y traslados entre bodegas.',
    logout: 'Cerrar sesión',
    loggingOut: 'Cerrando sesión…',
    logoutFailed: 'No pudimos cerrar la sesión. Intenta de nuevo.',
  },
  home: {
    greeting: 'Bienvenido, {name}',
    shortcuts: 'Accesos',
  },
  session: {
    loading: 'Cargando sesión…',
    loadFailed: 'No pudimos verificar tu sesión.',
    retry: 'Reintentar',
    expired: 'Tu sesión expiró. Inicia sesión de nuevo.',
  },
  login: {
    title: 'Iniciar sesión',
    email: 'Correo electrónico',
    password: 'Contraseña',
    submit: 'Iniciar sesión',
    submitting: 'Ingresando…',
    required: 'Este campo es obligatorio.',
  },
  // Etiquetas de rol: el código del rol nunca se muestra al usuario.
  roles: {
    auxiliar_farmacia: 'Auxiliar de farmacia',
    regente_farmacia: 'Regente de farmacia',
    medico: 'Médico',
    auditor: 'Auditor',
    admin: 'Administrador',
    unknown: 'Rol sin etiqueta',
  },
  // Mensajes por `code` de la API (forma de rechazo única, design D5).
  errors: {
    invalidCredentials: 'Correo o contraseña incorrectos.',
    tooManyAttempts: 'Demasiados intentos. Espera un momento antes de volver a intentar.',
    csrfExpired: 'La sesión de seguridad expiró. Recarga la página e intenta de nuevo.',
    network: 'No pudimos conectar con el servidor. Intenta de nuevo.',
    forbidden: 'No tienes permiso para realizar esta acción.',
    notFound: 'El recurso solicitado no existe.',
    validation: 'Revisa los datos ingresados.',
    unexpected: 'Ocurrió un error inesperado. Intenta de nuevo.',
    // Una línea por faltante (`shortages`); sin detalle, el texto general.
    insufficientStock: 'Stock insuficiente: {product} necesita {requested} y hay {available} disponibles.',
    insufficientStockGeneric: 'Stock insuficiente para completar la operación.',
    unknownProduct: 'un producto',
    lotExpired: 'El lote está vencido y no puede usarse.',
    prescriptionExpired: 'La prescripción está vencida y no se puede dispensar.',
    prescriptionExhausted: 'La prescripción ya fue dispensada por completo.',
    exceedsPrescription: 'La cantidad supera lo pendiente en la prescripción.',
    invalidAuthorizer:
      'Las credenciales del autorizador no son válidas o no tiene permiso para autorizar.',
    authorizerMustDiffer: 'El autorizador debe ser un regente distinto de quien dispensa.',
    authorizationRequired: 'Este medicamento requiere la autorización de un regente.',
    idempotencyKeyReused:
      'Esta confirmación ya se usó con otros datos. Revisa la asignación y confirma de nuevo.',
    segregationOfDuties: 'Quien solicitó el traslado no puede aprobarlo.',
    invalidTransferTransition:
      'El traslado cambió de estado mientras lo revisabas. Actualizamos la información.',
    // Solo la ruta del asistente tiene límite por minuto (`throttle:assistant`).
    tooManyRequests: 'Hiciste muchas preguntas seguidas. Espera un minuto e intenta de nuevo.',
    assistantUnavailable: 'El asistente no está disponible en este momento. Intenta más tarde.',
  },
  common: {
    retry: 'Reintentar',
    previous: 'Anterior',
    next: 'Siguiente',
    page: 'Página {page} de {total}',
    working: 'Procesando…',
    cancel: 'Cancelar',
    required: 'Este campo es obligatorio.',
    remove: 'Quitar',
  },
  // Menú de pantallas de operación (operator-workspace "Navegación por rol").
  nav: {
    label: 'Pantallas de operación',
    dispensations: 'Dispensación',
    transfers: 'Traslados',
    inventory: 'Inventario',
    kardex: 'Kardex',
    users: 'Usuarios',
    catalog: 'Catálogo',
    assistant: 'Asistente',
  },
  guard: {
    forbidden: 'No tienes permiso para ver esta pantalla.',
    backHome: 'Volver al inicio',
  },
  filters: {
    warehouse: 'Bodega',
    allWarehouses: 'Todas las bodegas',
    product: 'Producto',
    allProducts: 'Todos los productos',
    lot: 'Lote',
    allLots: 'Todos los lotes',
    lotNeedsProduct: 'Elige un producto primero',
  },
  inventory: {
    title: 'Inventario',
    description: 'Existencias por bodega, producto y lote con su vencimiento.',
    loading: 'Cargando inventario…',
    empty: 'No hay existencias para los filtros elegidos.',
    caption: 'Existencias por bodega y lote',
    columns: {
      warehouse: 'Bodega',
      product: 'Producto',
      lot: 'Lote',
      expiresOn: 'Vencimiento',
      quantity: 'Cantidad',
    },
    controlled: 'Control especial',
    expired: 'Vencido',
    // Alertas de RN-11: el resaltado sale solo de la API, nunca del reloj del navegador.
    alerts: {
      title: 'Alertas',
      loading: 'Cargando alertas…',
      failed: 'No pudimos cargar las alertas.',
      none: 'Sin alertas de vencimiento ni de stock mínimo.',
      expiringSummary: 'Lotes por vencer o vencidos: {count}. Se resaltan en la tabla.',
      expiresIn: 'Vence en {days} días',
      expiresInOne: 'Vence en 1 día',
      lowStockBadge: 'Bajo mínimo',
      lowStockTitle: 'Productos bajo mínimo',
      lowStockCaption: 'Productos por debajo del stock mínimo de su bodega',
      columns: {
        warehouse: 'Bodega',
        product: 'Producto',
        minimum: 'Mínimo',
        available: 'Disponible',
      },
    },
  },
  kardex: {
    title: 'Kardex',
    description: 'Movimientos de inventario, del más reciente al más antiguo.',
    loading: 'Cargando movimientos…',
    empty: 'No hay movimientos para los filtros elegidos.',
    caption: 'Movimientos del kardex',
    pagination: 'Paginación del kardex',
    system: 'Sistema',
    columns: {
      date: 'Fecha',
      type: 'Tipo',
      warehouse: 'Bodega',
      product: 'Producto',
      lot: 'Lote',
      quantity: 'Cantidad',
      balance: 'Saldo',
      user: 'Usuario',
      reason: 'Motivo',
    },
    // Tipos de movimiento (RN-06): nunca el literal de la API.
    types: {
      entrada: 'Entrada',
      salida_dispensacion: 'Salida por dispensación',
      salida_traslado: 'Salida por traslado',
      entrada_traslado: 'Entrada por traslado',
      ajuste: 'Ajuste',
    },
    unknownType: 'Movimiento',
  },
  // Pantalla Dispensación (dispensation-screen).
  dispensation: {
    title: 'Dispensación',
    description: 'Busca al paciente, revisa los lotes que asigna FEFO y confirma la entrega.',
    search: {
      label: 'Documento o nombre del paciente',
      submit: 'Buscar',
      hint: 'Enter busca; las flechas recorren los resultados y Enter abre la ficha.',
      tooShort: 'Escribe al menos 3 caracteres.',
      loading: 'Buscando pacientes…',
      empty: 'No encontramos pacientes con ese documento o nombre.',
      results: 'Pacientes encontrados',
    },
    patient: {
      loading: 'Cargando ficha del paciente…',
      title: 'Ficha del paciente',
      document: 'Documento',
      name: 'Nombre',
      birthDate: 'Fecha de nacimiento',
      phone: 'Teléfono',
      masked: 'Datos enmascarados',
      prescriptions: 'Prescripciones',
      noPrescriptions: 'Este paciente no tiene prescripciones.',
    },
    prescription: {
      title: 'Prescripción #{id}',
      validUntil: 'Vigencia: {date}',
      prescriber: 'Prescriptor: {name}',
      // Estados calculados por la API (RN-04): nunca el literal crudo.
      status: {
        vigente: 'Vigente',
        vencida: 'Vencida',
        agotada: 'Agotada',
      },
      unknownStatus: 'Sin estado',
      caption: 'Ítems de la prescripción',
      columns: {
        product: 'Producto',
        prescribed: 'Prescrita',
        dispensed: 'Dispensada',
        pending: 'Pendiente',
      },
      controlled: 'Control especial',
      dispense: 'Dispensar esta prescripción',
    },
    form: {
      title: 'Dispensar prescripción #{id}',
      warehouse: 'Bodega',
      chooseWarehouse: 'Elige una bodega',
      quantity: 'Cantidad de {product}',
      pending: 'Pendiente: {pending}',
      warehouseRequired: 'Elige una bodega.',
      quantitiesRequired: 'Indica al menos una cantidad.',
      quantityTooHigh: 'La cantidad no puede superar lo pendiente ({pending}).',
      quantityInvalid: 'Escribe un número entero entre 0 y {pending}.',
      preview: 'Ver lotes asignados',
      previewing: 'Calculando asignación…',
      previewNeeded: 'Pulsa "Ver lotes asignados" para revisar la asignación antes de confirmar.',
      cancel: 'Cancelar',
    },
    preview: {
      title: 'Lotes asignados (FEFO)',
      caption: 'Lotes asignados a {product}',
      columns: {
        lot: 'Lote',
        expiresOn: 'Vencimiento',
        quantity: 'Cantidad',
      },
      expiredExcluded: '{count} unidades en lotes vencidos no se usan.',
    },
    authorizer: {
      notice:
        'Medicamento de control especial: requiere autorización de un regente distinto de quien dispensa.',
      email: 'Correo del regente que autoriza',
      password: 'Contraseña del regente',
    },
    confirm: 'Confirmar dispensación',
    confirming: 'Confirmando…',
    recalculate: 'Recalcular asignación',
    success: {
      title: 'Dispensación registrada',
      caption: 'Líneas de la dispensación',
      columns: {
        product: 'Producto',
        lot: 'Lote',
        expiresOn: 'Vencimiento',
        quantity: 'Cantidad',
      },
      newDispensation: 'Nueva dispensación',
    },
  },
  // Pantalla Traslados (transfers-screen). Estados con los literales de RN-07 como clave.
  transfers: {
    title: 'Traslados',
    description: 'Traslados entre bodegas por lote, con aprobación y discrepancias de recepción.',
    loading: 'Cargando traslados…',
    empty: 'No hay traslados para este filtro.',
    caption: 'Traslados entre bodegas',
    pagination: 'Paginación de traslados',
    newTransfer: 'Nuevo traslado',
    number: 'Traslado #{id}',
    filters: {
      status: 'Estado',
      allStatuses: 'Todos los estados',
    },
    columns: {
      number: 'Número',
      origin: 'Origen',
      destination: 'Destino',
      status: 'Estado',
      date: 'Fecha',
    },
    status: {
      BORRADOR: 'Borrador',
      SOLICITADO: 'Solicitado',
      APROBADO: 'Aprobado',
      EN_TRANSITO: 'En tránsito',
      RECIBIDO: 'Recibido',
      RECIBIDO_PARCIAL: 'Recibido parcial',
      ANULADO: 'Anulado',
    },
    unknownStatus: 'Sin estado',
    form: {
      title: 'Nuevo traslado',
      origin: 'Bodega de origen',
      destination: 'Bodega de destino',
      chooseWarehouse: 'Elige una bodega',
      notes: 'Observaciones (opcional)',
      lines: 'Lotes a trasladar',
      lot: 'Lote {n}',
      chooseLot: 'Elige un lote',
      chooseOriginFirst: 'Elige el origen primero',
      lotOption: '{product} · Lote {lot} · vence {expiresOn} · disponible {available}',
      quantity: 'Cantidad {n}',
      addLine: 'Agregar lote',
      removeLine: 'Quitar lote {n}',
      loadingLots: 'Cargando lotes del origen…',
      noLots: 'La bodega de origen no tiene lotes disponibles.',
      submit: 'Crear traslado',
      submitting: 'Creando traslado…',
      cancel: 'Cancelar',
      sameWarehouse: 'El destino debe ser distinto del origen.',
      noLines: 'Agrega al menos un lote.',
      lotRequired: 'Elige un lote.',
      quantityInvalid: 'La cantidad debe ser un entero mayor que 0.',
    },
    detail: {
      back: 'Volver a traslados',
      loading: 'Cargando traslado…',
      notFound: 'No encontramos el traslado.',
      summary: 'Resumen',
      origin: 'Origen',
      destination: 'Destino',
      notes: 'Observaciones',
      noNotes: 'Sin observaciones',
      history: 'Seguimiento',
      actor: '{name} · {date}',
      unknownActor: 'Usuario',
      events: {
        created: 'Creado por',
        requested: 'Solicitado por',
        approved: 'Aprobado por',
        dispatched: 'Despachado por',
        received: 'Recibido por',
        voided: 'Anulado por',
        voidReason: 'Motivo de anulación',
      },
      lines: 'Líneas',
      linesCaption: 'Líneas del traslado',
      columns: {
        product: 'Producto',
        lot: 'Lote',
        expiresOn: 'Vencimiento',
        sent: 'Enviada',
        received: 'Recibida',
        shortage: 'Faltante',
        status: 'Estado',
      },
      notReceived: '—',
      discrepancies: 'Discrepancias',
      discrepanciesCaption: 'Faltantes de la recepción',
      discrepancyStatus: {
        pending: 'Pendiente',
        resolved: 'Resuelta',
      },
      requesterNotice: 'Lo solicitaste tú: otro regente debe aprobarlo.',
    },
    actions: {
      label: 'Acciones del traslado',
      request: 'Solicitar',
      approve: 'Aprobar',
      dispatch: 'Despachar',
      receive: 'Recibir',
      void: 'Anular',
      working: 'Procesando…',
    },
    dispatch: {
      title: 'Despachar traslado',
      description: 'El stock saldrá de {origin} y quedará en tránsito.',
      confirm: 'Confirmar despacho',
      insufficientStock: 'Stock insuficiente en la bodega de origen para despachar este traslado.',
    },
    receive: {
      title: 'Recibir traslado',
      quantity: 'Cantidad recibida de {product} · Lote {lot}',
      sent: 'Enviada: {sent}',
      discrepancyNotice: 'Lo no recibido quedará como discrepancia pendiente.',
      tooHigh: 'No puede superar lo enviado ({sent}).',
      invalid: 'Escribe un número entero entre 0 y {sent}.',
      confirm: 'Confirmar recepción',
      cancel: 'Cancelar',
    },
    void: {
      title: 'Anular traslado',
      description: 'El traslado quedará anulado y no podrá continuar.',
      reason: 'Motivo',
      reasonRequired: 'Escribe el motivo de la anulación.',
      confirm: 'Confirmar anulación',
    },
  },
  // Pantalla Asistente (assistant-screen). Etiquetas por literal de la API como clave: nunca el
  // literal crudo en pantalla.
  assistant: {
    title: 'Asistente de inventario',
    description: 'Pregunta en español por existencias, vencimientos, stock mínimo y traslados.',
    question: 'Tu pregunta',
    counter: '{n}/500',
    hint: 'Enter envía; Shift+Enter agrega una línea.',
    submit: 'Preguntar',
    submitting: 'Consultando…',
    pending: 'Consultando al asistente…',
    tooShort: 'Escribe al menos 3 caracteres.',
    privacy:
      'No escribas nombres ni documentos de pacientes: el asistente solo responde sobre inventario y traslados.',
    examplesTitle: 'Preguntas de ejemplo',
    examples: [
      '¿Cuánto stock hay de acetaminofén en la farmacia central?',
      '¿Qué lotes de acetaminofén vencen en los próximos 60 días en la farmacia central?',
      '¿Qué productos están por debajo del stock mínimo?',
      '¿Cuántos traslados hay en tránsito?',
    ],
    empty: 'Aún no has hecho preguntas. Prueba con uno de los ejemplos.',
    history: 'Preguntas recientes',
    outcomes: {
      answered: 'Respondida',
      no_results: 'Sin resultados',
      out_of_scope: 'Fuera de alcance',
      not_permitted: 'Sin permiso',
      unknown: 'Sin respuesta',
    },
    toolCalls: 'Consultas hechas',
    noToolCalls: 'Sin consultas a herramientas.',
    tools: {
      get_stock: 'Existencias',
      find_expiring_lots: 'Lotes por vencer',
      get_low_stock_alerts: 'Stock bajo mínimo',
      get_transfer_status: 'Estado de traslados',
    },
    unknownTool: 'Herramienta fuera del catálogo',
    callStatus: {
      ok: 'Consultada',
      denied: 'Sin permiso',
      rejected: 'Rechazada',
      invalid_arguments: 'Argumentos inválidos',
      failed: 'Falló',
    },
    unknownCallStatus: 'Sin estado',
    arguments: {
      product: 'Producto',
      warehouse: 'Bodega',
      days: 'Días',
      transfer_id: 'Traslado',
      status: 'Estado',
    },
    unknownArgument: 'Dato',
    argument: '{label}: {value}',
  },
  // Pantalla Usuarios (admin-screens): la contraseña nunca se muestra ni se lista.
  users: {
    title: 'Usuarios',
    description: 'Cuentas del personal con su rol. Crea un usuario nuevo con su contraseña inicial.',
    loading: 'Cargando usuarios…',
    empty: 'No hay usuarios registrados.',
    caption: 'Usuarios registrados',
    columns: {
      name: 'Nombre',
      email: 'Correo electrónico',
      role: 'Rol',
    },
    form: {
      title: 'Nuevo usuario',
      name: 'Nombre',
      email: 'Correo electrónico',
      password: 'Contraseña',
      passwordHint: 'Mínimo 8 caracteres.',
      role: 'Rol',
      chooseRole: 'Selecciona un rol',
      submit: 'Crear usuario',
      submitting: 'Creando usuario…',
    },
    created: 'Usuario {name} creado.',
  },
  // Pantalla Catálogo (admin-screens): bodegas y productos con alta y edición en contexto.
  catalog: {
    title: 'Catálogo',
    description: 'Bodegas y productos del inventario. Crea y edita sus datos.',
    edit: 'Editar',
    editLabel: 'Editar {name}',
    save: 'Guardar cambios',
    saving: 'Guardando…',
    cancel: 'Cancelar',
    actions: 'Acciones',
    yes: 'Sí',
    no: 'No',
    warehouses: {
      title: 'Bodegas',
      loading: 'Cargando bodegas…',
      empty: 'No hay bodegas registradas.',
      caption: 'Bodegas registradas',
      columns: {
        code: 'Código',
        name: 'Nombre',
      },
      form: {
        title: 'Nueva bodega',
        editTitle: 'Editar bodega {name}',
        code: 'Código',
        name: 'Nombre',
        submit: 'Crear bodega',
        submitting: 'Creando bodega…',
      },
      created: 'Bodega {name} creada.',
      updated: 'Bodega {name} actualizada.',
    },
    products: {
      title: 'Productos',
      loading: 'Cargando productos…',
      empty: 'No hay productos registrados.',
      caption: 'Productos registrados',
      noPresentation: 'Sin presentación',
      columns: {
        code: 'Código',
        name: 'Nombre',
        presentation: 'Presentación',
        controlled: 'Control especial',
      },
      form: {
        title: 'Nuevo producto',
        editTitle: 'Editar producto {name}',
        code: 'Código',
        name: 'Nombre',
        presentation: 'Presentación (opcional)',
        controlled: 'Medicamento de control especial',
        submit: 'Crear producto',
        submitting: 'Creando producto…',
      },
      created: 'Producto {name} creado.',
      updated: 'Producto {name} actualizado.',
    },
  },
  a11y: {
    loading: 'Cargando',
  },
} as const

export type RoleCode = Exclude<keyof typeof strings.roles, 'unknown'>

// Completa una plantilla del módulo con valores de datos (nombre del usuario, etc.).
export function format(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => values[key] ?? match)
}

// Etiqueta en español de un rol; un código desconocido nunca se muestra crudo.
export function roleLabel(role: string): string {
  return Object.hasOwn(strings.roles, role) && role !== 'unknown'
    ? strings.roles[role as RoleCode]
    : strings.roles.unknown
}
